# Site settings
author: Esteban Llerena
title: beginning my software engineer course 
header-img: img/home-bg.png
email: estebanllerena@gmail.com
copyright_name: Esteban Llerena
description: > # this means to ignore newlines until "baseurl:"
  excited 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ellerena1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
